# Generated by Django 6.0.6 on 2026-06-10 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('work_time', models.DurationField()),
                ('work_duration', models.IntegerField()),
                ('job_title', models.CharField(max_length=200)),
                ('working_condition', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time')], default='full_time', max_length=20)),
                ('work_schedule_and_working_hours', models.CharField(choices=[('6/1', '6/1'), ('5/2', '5/2'), ('4/3', '4/3'), ('3/4', '3/4'), ('2/5', '2/5'), ('1/6', '1/6')], default='6/1', max_length=20)),
                ('work_field', models.CharField(choices=[('permament', 'har doimiy'), ('temporary', 'vaqtinchalik')], default='full_time', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('salary', models.IntegerField()),
                ('required_experience', models.IntegerField()),
                ('work_time', models.DurationField()),
                ('job_title', models.CharField(max_length=200)),
                ('requirements_of_job', models.TextField()),
                ('working_condition', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time')], default='full_time', max_length=20)),
                ('work_schedule_and_working_hours', models.CharField(choices=[('6/1', '6/1'), ('5/2', '5/2'), ('4/3', '4/3'), ('3/4', '3/4'), ('2/5', '2/5'), ('1/6', '1/6')], default='6/1', max_length=20)),
                ('work_field', models.CharField(choices=[('permament', 'har doimiy'), ('temporary', 'vaqtinchalik')], default='full_time', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('qidirilyapti', 'Qidirilyapti'), ('topilgan', 'Topilgan')], default='qidirilyapti', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('phone_number2', models.CharField(blank=True, max_length=20, null=True)),
                ('experience', models.IntegerField()),
                ('wanted_salary', models.IntegerField()),
                ('wanted_work_time', models.DurationField()),
                ('wanted_working_condition', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time')], default='full_time', max_length=20)),
                ('wanted_work_schedule_and_working_hours', models.CharField(choices=[('6/1', '6/1'), ('5/2', '5/2'), ('4/3', '4/3'), ('3/4', '3/4'), ('2/5', '2/5'), ('1/6', '1/6')], default='6/1', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('qidirilyapti', 'Qidirilyapti'), ('topilgan', 'Topilgan')], default='qidirilyapti', max_length=20)),
            ],
        ),
    ]
