# Generated by Django 6.0.6 on 2026-06-10 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internship',
            name='working_condition',
        ),
        migrations.RemoveField(
            model_name='job',
            name='working_condition',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='wanted_working_condition',
        ),
    ]
