# Generated by Django 6.0.6 on 2026-06-10 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_remove_internship_working_condition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='working_condition',
            field=models.CharField(choices=[('full_time', 'toliq vaqt'), ('part_time', 'yarim vaqt'), ('remote', 'masofaviy')], default='full_time', max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='working_condition',
            field=models.CharField(choices=[('full_time', 'toliq vaqt'), ('part_time', 'yarim vaqt'), ('remote', 'masofaviy')], default='full_time', max_length=20),
        ),
        migrations.AddField(
            model_name='resume',
            name='wanted_working_condition',
            field=models.CharField(choices=[('full_time', 'toliq vaqt'), ('part_time', 'yarim vaqt'), ('remote', 'masofaviy')], default='full_time', max_length=20),
        ),
    ]
