# Generated by Django 6.0.6 on 2026-06-10 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_internship_working_condition_job_working_condition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship',
            name='work_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='work_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='resume',
            name='wanted_work_time',
            field=models.TimeField(),
        ),
    ]
