# Generated by Django 6.0.6 on 2026-09-05 18:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_internship_work_time_alter_job_work_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='phone_number',
            field=models.CharField(default='', max_length=20, validators=[django.core.validators.RegexValidator(message='Введите корректный номер телефона: 8–15 цифр, можно использовать +, пробелы, дефисы и скобки.', regex='^\\+?(?=(?:\\D*\\d){8,15}\\D*$)[0-9][0-9\\s().-]*[0-9]$')]),
        ),
        migrations.AddField(
            model_name='internship',
            name='phone_number2',
            field=models.CharField(blank=True, default='', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Введите корректный номер телефона: 8–15 цифр, можно использовать +, пробелы, дефисы и скобки.', regex='^\\+?(?=(?:\\D*\\d){8,15}\\D*$)[0-9][0-9\\s().-]*[0-9]$')]),
        ),
        migrations.AddField(
            model_name='job',
            name='phone_number',
            field=models.CharField(default='', max_length=20, validators=[django.core.validators.RegexValidator(message='Введите корректный номер телефона: 8–15 цифр, можно использовать +, пробелы, дефисы и скобки.', regex='^\\+?(?=(?:\\D*\\d){8,15}\\D*$)[0-9][0-9\\s().-]*[0-9]$')]),
        ),
        migrations.AddField(
            model_name='job',
            name='phone_number2',
            field=models.CharField(blank=True, default='', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Введите корректный номер телефона: 8–15 цифр, можно использовать +, пробелы, дефисы и скобки.', regex='^\\+?(?=(?:\\D*\\d){8,15}\\D*$)[0-9][0-9\\s().-]*[0-9]$')]),
        ),
        migrations.AlterField(
            model_name='resume',
            name='phone_number',
            field=models.CharField(default='', max_length=20, validators=[django.core.validators.RegexValidator(message='Введите корректный номер телефона: 8–15 цифр, можно использовать +, пробелы, дефисы и скобки.', regex='^\\+?(?=(?:\\D*\\d){8,15}\\D*$)[0-9][0-9\\s().-]*[0-9]$')]),
        ),
        migrations.AlterField(
            model_name='resume',
            name='phone_number2',
            field=models.CharField(blank=True, default='', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Введите корректный номер телефона: 8–15 цифр, можно использовать +, пробелы, дефисы и скобки.', regex='^\\+?(?=(?:\\D*\\d){8,15}\\D*$)[0-9][0-9\\s().-]*[0-9]$')]),
        ),
    ]
