# Generated by Django 6.0.6 on 2026-09-09 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_internship_owner_job_owner_resume_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='status',
            field=models.CharField(choices=[('qidirilyapti', 'Qidirilyapti'), ('topilgan', 'Topilgan')], default='qidirilyapti', max_length=20),
        ),
    ]
