# Generated by Django 6.0.6 on 2026-09-09 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_internship_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship',
            name='status',
            field=models.CharField(choices=[('qidirilyapti', 'Still looking'), ('topilgan', 'Not looking')], default='qidirilyapti', max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('qidirilyapti', 'Still looking'), ('topilgan', 'Not looking')], default='qidirilyapti', max_length=20),
        ),
        migrations.AlterField(
            model_name='resume',
            name='status',
            field=models.CharField(choices=[('qidirilyapti', 'Still looking'), ('topilgan', 'Not looking')], default='qidirilyapti', max_length=20),
        ),
    ]
