# Generated by Django 6.0.6 on 2026-09-11 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_alter_internship_status_alter_job_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internship',
            name='work_time',
        ),
        migrations.AddField(
            model_name='internship',
            name='work_time',
            field=models.IntegerField(default=8),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='job',
            name='work_time',
        ),
        migrations.AddField(
            model_name='job',
            name='work_time',
            field=models.IntegerField(default=8),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='resume',
            name='wanted_work_time',
        ),
        migrations.AddField(
            model_name='resume',
            name='wanted_work_time',
            field=models.IntegerField(default=8),
            preserve_default=False,
        ),
    ]
