# Generated by Django 6.0.6 on 2026-09-14 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_internship_company_logo_job_company_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountprofile',
            name='role',
            field=models.CharField(choices=[('company', 'Company'), ('worker', 'Worker'), ('creator', 'Creator')], max_length=20),
        ),
    ]
