# Generated by Django 6.0.6 on 2026-09-26 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_company_photo_and_work_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship',
            name='work_field',
            field=models.CharField(choices=[('permament', 'Permanent'), ('temporary', 'Temporary')], default='full_time', max_length=20),
        ),
        migrations.AlterField(
            model_name='internship',
            name='working_condition',
            field=models.CharField(choices=[('full_time', 'Full time'), ('part_time', 'Part time'), ('remote', 'Remote')], default='full_time', max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='work_field',
            field=models.CharField(choices=[('permament', 'Permanent'), ('temporary', 'Temporary')], default='full_time', max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='working_condition',
            field=models.CharField(choices=[('full_time', 'Full time'), ('part_time', 'Part time'), ('remote', 'Remote')], default='full_time', max_length=20),
        ),
        migrations.AlterField(
            model_name='resume',
            name='wanted_working_condition',
            field=models.CharField(choices=[('full_time', 'Full time'), ('part_time', 'Part time'), ('remote', 'Remote')], default='full_time', max_length=20),
        ),
    ]
